'''
Code generated by OpenAI's ChatGPT.

__     _______     _______ _    _ 
\ \   / /  __ \ /\|__   __| |  | |
 \ \_/ /| |__) /  \  | |  | |__| |
  \   / |  ___/ /\ \ | |  |  __  |
   | |  | |  / ____ \| |  | |  | |
   |_|  |_| /_/    \_\_|  |_|  |_|

Author: OpenAI's ChatGPT
'''

import os
import librosa
from pydub import AudioSegment

# Define the path to the 'output' directory
dir_path = 'output/'

# Iterate over every file in the directory
for filename in os.listdir(dir_path):
    # Check if this file is an mp3
    if filename.endswith('.mp3'):
        # Load the mp3 file
        y, sr = librosa.load(dir_path + filename, sr=None)
        
        # Slow down the audio by a factor of 0.9
        y_slow = librosa.effects.time_stretch(0.5)

        # Save the audio back to the original file
        librosa.output.write_wav(dir_path + filename, y_slow, sr)
